# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - exhaustive
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - modernize
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  settings:
    revive:
      rules:
        - name: comment-spacings
    exhaustive:
      check:
        - switch
        - map
    usetesting:
      os-chdir: true
      context-background: true
      context-todo: true
    modernize:
      disable:
        - embedlit
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - contextcheck
          - errcheck
          - noctx
          - dupl
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
