{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cache-csi-driver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cache-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cache-csi-driver.healthControllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cache-csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: health-controller
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cache-csi-driver.resourceName" (dict "root" . "suffix" "scheduler") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cache-csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
automountServiceAccountToken: true
