//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheClass) DeepCopyInto(out *CacheClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheClass.
func (in *CacheClass) DeepCopy() *CacheClass {
	if in == nil {
		return nil
	}
	out := new(CacheClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheClassList) DeepCopyInto(out *CacheClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CacheClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheClassList.
func (in *CacheClassList) DeepCopy() *CacheClassList {
	if in == nil {
		return nil
	}
	out := new(CacheClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheClassSpec) DeepCopyInto(out *CacheClassSpec) {
	*out = *in
	out.MaxBytes = in.MaxBytes.DeepCopy()
	out.Retention = in.Retention
	in.Quota.DeepCopyInto(&out.Quota)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheClassSpec.
func (in *CacheClassSpec) DeepCopy() *CacheClassSpec {
	if in == nil {
		return nil
	}
	out := new(CacheClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicy) DeepCopyInto(out *QuotaPolicy) {
	*out = *in
	out.DefaultMaxBytes = in.DefaultMaxBytes.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicy.
func (in *QuotaPolicy) DeepCopy() *QuotaPolicy {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicy)
	in.DeepCopyInto(out)
	return out
}
